// Items types
export const SET_ITEMS = 'SET_ITEMS'

// Filter types
export const SET_TEXT_FILTER = 'SET_TEXT_FILTER'
export const SET_MAX_MR = 'SET_MAX_MR'
export const SET_HIDE_OWNED = 'SET_HIDE_OWNED'
export const SET_HIDE_MASTERED = 'SET_HIDE_MASTERED'
export const SET_WEAPON_SORT = 'SET_WEAPON_SORT'
export const SET_WARFRAME_SORT = 'SET_WARFRAME_SORT'
export const SET_COMPANION_SORT = 'SET_COMPANION_SORT'
export const SET_VEHICLE_SORT = 'SET_VEHICLE_SORT'

// User types
export const SET_USER_OWNED = 'SET_USER_OWNED'
export const ADD_OWNED = 'ADD_OWNED'
export const ADD_MASTERED = 'ADD_MASTERED'
export const SET_USER_MASTERED = 'SET_USER_MASTERED'
export const REMOVE_OWNED = 'REMOVE_OWNED'
export const REMOVE_MASTERED = 'REMOVE_MASTERED'
export const SET_STAR_CHART_MASTERY = 'SET_STAR_CHART_MASTERY'
export const EDIT_INTRINSICS = 'EDIT_INTRINSICS'
